const baza = [
    {
        id: 1,
        username: "ali_uz",
        fullName: "Ali Valiyev",
        firstName: "Ali",
        lastName: "Valiyev",
        middleName: "Anvar o‘g‘li",
        birthDate: "2005-04-12",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Toshkent shahri",
        district: "Chilonzor tumani",
        address: "Bunyodkor ko‘chasi, 15-uy, 24-xonadon",
        phone: "+998 90 123 45 67",
        email: "ali.valiyev@example.com",
        passport: {
            series: "AA",
            number: "1029384",
            issuedBy: "Toshkent shahar Chilonzor IIB",
            issuedDate: "2022-05-20"
        },
        age: 20,
        registeredAt: "2026-09-10",
        password: "test1234"
    },
    {
        id: 2,
        username: "malika_k",
        fullName: "Malika Karimova",
        firstName: "Malika",
        lastName: "Karimova",
        middleName: "Rustam qizi",
        birthDate: "2003-08-25",
        gender: "Ayol",
        country: "O‘zbekiston",
        region: "Samarqand viloyati",
        district: "Samarqand shahri",
        address: "Registon ko‘chasi, 8-uy",
        phone: "+998 93 456 78 90",
        email: "malika.karimova@example.com",
        passport: {
            series: "AB",
            number: "3847291",
            issuedBy: "Samarqand shahar IIB",
            issuedDate: "2021-09-14"
        },
        age: 22,
        registeredAt: "2026-09-11",
        password: "password123"
    },
    {
        id: 3,
        username: "bobur_m",
        fullName: "Bobur Mirzayev",
        firstName: "Bobur",
        lastName: "Mirzayev",
        middleName: "Ikrom o‘g‘li",
        birthDate: "1999-11-14",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Farg‘ona viloyati",
        district: "Qo‘qon shahri",
        address: "Istiqlol ko‘chasi, 45-uy, 12-xonadon",
        phone: "+998 91 234 56 78",
        email: "bobur.mirzayev@example.com",
        passport: {
            series: "AC",
            number: "5918234",
            issuedBy: "Qo‘qon shahar IIB",
            issuedDate: "2019-12-05"
        },
        age: 26,
        registeredAt: "2026-09-12",
        password: "password123"
    },
    {
        id: 4,
        username: "nodira_sh",
        fullName: "Nodira Shukurova",
        firstName: "Nodira",
        lastName: "Shukurova",
        middleName: "Jamshid qizi",
        birthDate: "2001-02-18",
        gender: "Ayol",
        country: "O‘zbekiston",
        region: "Buxoro viloyati",
        district: "Buxoro shahri",
        address: "Bahouddin Naqshband ko‘chasi, 12-uy",
        phone: "+998 97 345 67 89",
        email: "nodira.shukurova@example.com",
        passport: {
            series: "AD",
            number: "7482910",
            issuedBy: "Buxoro shahar IIB",
            issuedDate: "2020-03-22"
        },
        age: 24,
        registeredAt: "2026-09-13",
        password: "password123"
    },
    {
        id: 5,
        username: "jasur_bek",
        fullName: "Jasurbek Toirov",
        firstName: "Jasurbek",
        lastName: "Toirov",
        middleName: "Sherzod o‘g‘li",
        birthDate: "1998-06-30",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Andijon viloyati",
        district: "Asaka tumani",
        address: "Bobur shoh ko‘chasi, 77-uy",
        phone: "+998 94 567 89 01",
        email: "jasur.toirov@example.com",
        passport: {
            series: "AE",
            number: "8392014",
            issuedBy: "Asaka tumani IIB",
            issuedDate: "2018-07-10"
        },
        age: 27,
        registeredAt: "2026-09-14",
        password: "password123"
    },
    {
        id: 6,
        username: "dilnoza_a",
        fullName: "Dilnoza Axmedova",
        firstName: "Dilnoza",
        lastName: "Axmedova",
        middleName: "Otabek qizi",
        birthDate: "2004-10-05",
        gender: "Ayol",
        country: "O‘zbekiston",
        region: "Namangan viloyati",
        district: "Namangan shahri",
        address: "Uychi ko‘chasi, 33-uy, 5-xonadon",
        phone: "+998 95 678 90 12",
        email: "dilnoza.axmedova@example.com",
        passport: {
            series: "AF",
            number: "9283741",
            issuedBy: "Namangan shahar IIB",
            issuedDate: "2022-11-19"
        },
        age: 21,
        registeredAt: "2026-09-15",
        password: "password123"
    },
    {
        id: 7,
        username: "shaxzod_x",
        fullName: "Shaxzod Xolmatov",
        firstName: "Shaxzod",
        lastName: "Xolmatov",
        middleName: "Dilshod o‘g‘li",
        birthDate: "2000-01-22",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Qashqadaryo viloyati",
        district: "Qarshi shahri",
        address: "Nasaf ko‘chasi, 19-uy",
        phone: "+998 99 789 01 23",
        email: "shaxzod.xolmatov@example.com",
        passport: {
            series: "AG",
            number: "1928374",
            issuedBy: "Qarshi shahar IIB",
            issuedDate: "2019-02-15"
        },
        age: 25,
        registeredAt: "2026-09-16",
        password: "password123"
    },
    {
        id: 8,
        username: "gulnoza_r",
        fullName: "Gulnoza Rahimova",
        firstName: "Gulnoza",
        lastName: "Rahimova",
        middleName: "Farxod qizi",
        birthDate: "2002-07-19",
        gender: "Ayol",
        country: "O‘zbekiston",
        region: "Xorazm viloyati",
        district: "Urganch shahri",
        address: "Al-Xorazmiy ko‘chasi, 5-uy",
        phone: "+998 90 890 12 34",
        email: "gulnoza.rahimova@example.com",
        passport: {
            series: "AH",
            number: "4829103",
            issuedBy: "Urganch shahar IIB",
            issuedDate: "2021-08-30"
        },
        age: 23,
        registeredAt: "2026-09-17",
        password: "password123"
    },
    {
        id: 9,
        username: "sardor_o",
        fullName: "Sardor Olimov",
        firstName: "Sardor",
        lastName: "Olimov",
        middleName: "Baxtiyor o‘g‘li",
        birthDate: "1997-03-08",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Surxondaryo viloyati",
        district: "Termiz shahri",
        address: "At-Termiziy ko‘chasi, 62-uy",
        phone: "+998 93 901 23 45",
        email: "sardor.olimov@example.com",
        passport: {
            series: "AI",
            number: "6372819",
            issuedBy: "Termiz shahar IIB",
            issuedDate: "2017-04-12"
        },
        age: 28,
        registeredAt: "2026-09-18",
        password: "password123"
    },
    {
        id: 10,
        username: "sevara_y",
        fullName: "Sevara Yo‘ldosheva",
        firstName: "Sevara",
        lastName: "Yo‘ldosheva",
        middleName: "Alisher qizi",
        birthDate: "2005-12-01",
        gender: "Ayol",
        country: "O‘zbekiston",
        region: "Toshkent viloyati",
        district: "Chirchiq shahri",
        address: "Lomonosov ko‘chasi, 14-uy, 7-xonadon",
        phone: "+998 91 012 34 56",
        email: "sevara.yuldosheva@example.com",
        passport: {
            series: "AJ",
            number: "7382910",
            issuedBy: "Chirchiq shahar IIB",
            issuedDate: "2023-01-18"
        },
        age: 20,
        registeredAt: "2026-09-19",
        password: "password123"
    },
    {
        id: 11,
        username: "umid_n",
        fullName: "Umidbek Nazarov",
        firstName: "Umidbek",
        lastName: "Nazarov",
        middleName: "Qahramon o‘g‘li",
        birthDate: "1996-09-15",
        gender: "Erkak",
        country: "O‘zbekiston",
        region: "Navoiy viloyati",
        district: "Navoiy shahri",
        address: "G‘alaba shoh ko‘chasi, 101-uy",
        phone: "+998 94 123 78 90",
        email: "umid.nazarov@example.com",
        passport: {
            series: "AK",
            number: "8472915",
            issuedBy: "Navoiy shahar IIB",
            issuedDate: "2016-10-09"
        },
        age: 29,
        registeredAt: "2026-09-20",
        password: "password123"
    }
];

module.exports = baza;
